# Generated by Django 6.0.3 on 2026-03-13 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('type_of_issue', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('progress', 'In Progress'), ('hold', 'On Hold'), ('done', 'Done')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
